### ISSUE TITLE
Language updating when there is a newer version in AMOS

### ISSUE THREAD

**Issue by ramonovelar** [UNIMOODLE/moodle-local_mail#7]
The plugin only takes the strings in the plugin folder (moodle/local/mail/lang/..). When new versions are downloaded from AMOS (https://lang.moodle.org/local/amos) to moodledata (/moodledata/lang/), these new strings are ignored and the application shows the strings in the plugin folder. If the folder of one particular language is removed from the plugin folder, the strings appear in english.
We ask this behaviour to be changed, so that strings in moodledata replace those in the plugin folder (moodle/local/mail/lang/..).

Many thanks,

**Comment by reskit** [comment]
Hi @ramonovelar,

UNIMOODLE requested that the plugin translations must include Catalan, Spanish, Basque and Galician languages.
When we reviewed the translations uploaded to AMOS for our plugin, we were surprised by the poor quality of the community-provided translations, given this situation, we decided not to accept the AMOS modifications for the aforementioned languages.
If you wish to change any language strings of the plugin, you can do so through "Site administration > Language > Language customisation".
