### ISSUE TITLE
Violation of Moodle String API

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_mail#8]
There is specific code to override the use of language packs for a set of languages ( 'ca', 'es', 'eu', 'gl').
This modifies the expected behaviour of the plugin and violates specification/conventions and interaction with AMOS.

> "There is no need to include languages other than the default English, as almost all approved [plugin strings will be automatically imported into AMOS](https://lang.moodle.org/mod/forum/discuss.php?d=2485) for translation by the language packs translators."

Expected behaviour:

* Plugin must use standard String API.
* Language packages should be maintainable via AMOS.
* However, files for spanish oficial languages can be distributed with the plugin source code for reference as it is not a violation of the String API.
* classes/output/strings.php should be deprecated.

I'll submit this issue to Gitlab to ensure traceability.

Best regards.

**Comment by reskit** [comment]
We are going to upload the Catalan, Spanish, Basque, and Galician language strings from the plugin to AMOS.
From now on, our focus will be solely on updating the English language strings, and we'll cease updating the other languages.
The next version of the plugin will only include the English language and all language strings, without exception, will be updated via AMOS.

**Comment by juacas** [comment]
I think this is a reasonable option.
However, I have received feedback that the translation in AMOS for some languages (e.g. Basque) is much better than the one we have now in the repository.

When uploading the strings to AMOS, we will have to negotiate with the translators on a case-by-case basis. I'm afraid it may be unnecessary work.

I propose to simply remove the String API bypass and let the community edit the Langpacks. Since they take precedence over local strings, there should be no problem.

In any case, case closed for me.
